image:
  file: .docker/gitpod/Dockerfile

vscode:
  extensions:
    - leanprover.lean4
    - mvllow.rose-pine

tasks:
  - init: |
      lake exe cache get && lake build Library && lake build AutograderLib
    command: |
      PATH="$PATH:/workspace/math2001/scripts"
